export const URL_LIST_REQUEST = 'URL_LIST_REQUEST'
export const URL_LIST_SUCCESS = 'URL_LIST_SUCCESS'
export const URL_LIST_FAIL = 'URL_LIST_FAIL'

export const URL_DETAILS_REQUEST = 'URL_DETAILS_REQUEST'
export const URL_DETAILS_SUCCESS = 'URL_DETAILS_SUCCESS'
export const URL_DETAILS_FAIL = 'URL_DETAILS_FAIL'

export const URL_CREATE_REQUEST = 'URL_CREATE_REQUEST'
export const URL_CREATE_SUCCESS = 'URL_CREATE_SUCCESS'
export const URL_CREATE_FAIL = 'URL_CREATE_FAIL'
export const URL_CREATE_RESET = 'URL_CREATE_RESET'
